import { ScrollView, Button, CheckBox, SpinBox, Slider, GroupBox, LineEdit, StandardListView,
    ComboBox, HorizontalBox, VerticalBox, GridBox, TabWidget, TextEdit } from "std-widgets.slint";

export struct MousePos := {
    x: length,
    y: length,
}

App := Window {
    preferred-width: 1200px;
    preferred-height: 800px;
    title: "Volume app";

    property<int> frame_time;

    property<image> render_target;
    callback send_rendered_frame();

    callback render_area_mp(MousePos) -> MousePos;

    // Just declaration, body is in Rust code
    callback render_area_move_event(MousePos);
    callback render_key_pressed <=> render_key_handler.key-pressed;

    callback x_slider_new_value <=> x_slider.changed; // float
    callback y_slider_new_value <=> y_slider.changed; // float
    callback z_slider_new_value <=> z_slider.changed; // float

    callback render_area_pointer_event <=> render_area.pointer-event;

    callback load_file <=> load_file_button.clicked;
    callback load_folder <=> load_folder_button.clicked;

    HorizontalLayout {
        padding-left: 10px;
        spacing: 20px;
        TabWidget {
            width: 390px;
            Tab {
                title: "Load";
                VerticalLayout {
                    alignment: start;
                    padding-top: 20px;
                    spacing: 10px;

                    load_file_button := Button { 
                        text: "Load from a file";
                        
                    }
                    load_folder_button := Button { 
                        text: "Load from a folder";
                    }
                }
            }
            Tab {
                title: "Controls";
                VerticalBox {
                    alignment: start;
                    GroupBox {
                        title: "x";
                        x_slider := Slider {
                            minimum: -1000;
                            maximum: 1000;
                            value: 0;
                        }
                    }   
                    GroupBox {
                        title: "y";
                        y_slider := Slider {
                            minimum: -1000;
                            maximum: 1000;
                            value: 0;
                        }
                    }  
                    GroupBox {
                        title: "z";
                        z_slider := Slider {
                            minimum: -1000;
                            maximum: 1000;
                            value: 0;
                        }
                    }  
                }
            }
            Tab {
                title: "Transfer function";
            }
        }

        VerticalLayout {

            width: 700px;
            height: 700px;
            padding-top: 50px;
            padding-bottom: 50px;
            
            RenTar := Image {
                source: root.render_target;
                max-width: 700px;
                max-height: 700px;

                Rectangle { 
                    x: 50px; // offset to corner of render screen
                    y: 0px;
                    width: 40px;
                    height: 20px;
                    Text { 
                        text: root.frame_time;
                        font-size: 11pt;
                        color: red;
                    }
                }
                
                render_area := TouchArea {
                    width: parent.width;
                    height: parent.height;

                    forward-focus: render_key_handler;

                    render_key_handler := FocusScope {
                    }
                    
                    moved => {
                        root.render_area_move_event({ x: self.mouse-x, y: self.mouse-y})
                    }
                }
            }
        }
    }
}