import { ScrollView, Button, CheckBox, SpinBox, Slider, GroupBox, LineEdit, StandardListView,
    ComboBox, HorizontalBox, VerticalBox, GridBox, TabWidget, TextEdit, AboutSlint } from "std-widgets.slint";

App := Window {
    preferred-width: 1000px;
    preferred-height: 800px;
    title: "Volume app";
    icon: @image-url("../../logo/slint-logo-small-light-128x128.png");

    property<image> render_target;
    callback send_rendered_frame();

    property<length> render_area_mouse_x <=> render_area.mouse-x;
    property<length> render_area_mouse_y <=> render_area.mouse-y;
    callback render_area_pointer_event <=> render_area.pointer-event;
    callback render_area_moved_event <=> render_area.moved;

    VerticalBox {
        HorizontalBox {
            Text {
                text: "Below are some of the standard widgets that application developers can easily re-use.";
                wrap: word-wrap;
            }

            VerticalLayout {
                alignment: start;
                disable-toggle := CheckBox {
                    checked: false;
                    text: "Disable Widgets";
                }
            }
        }

        TabWidget {
            Tab {
                title: "Controls";
                VerticalBox {
                    alignment: start;
                    HorizontalBox {
                        alignment: start;
                        GroupBox {
                            title: "Button";
                            enabled: !disable-toggle.checked;

                            Button {
                                text: "Regular Button";
                                enabled: !disable-toggle.checked;
                            }
                        }

                        GroupBox {
                            title: "Button with Icon";
                            enabled: !disable-toggle.checked;

                            Button {
                                text: "Regular Button";
                                icon: @image-url("thumbsup.png");
                                enabled: !disable-toggle.checked;
                            }
                        }

                        GroupBox {
                            title: "CheckBox";
                            enabled: !disable-toggle.checked;
                            checkbox := CheckBox {
                                text: checkbox.checked ? "(checked)" : "(unchecked)";
                                checked: true;
                                enabled: !disable-toggle.checked;
                            }
                        }

                        RenTar := Image {
                            source: root.render_target;
                            width: 700px;

                            render_area := TouchArea {
                                width: parent.width;
                                height: parent.height;
                            }
                        }
                    }

                    HorizontalBox {
                        alignment: start;
                        GroupBox {
                            title: "SpinBox";
                            enabled: !disable-toggle.checked;
                            SpinBox {
                                value: 42;
                                enabled: !disable-toggle.checked;
                            }
                        }

                        GroupBox {
                            title: "ComboBox";
                            enabled: !disable-toggle.checked;
                            ComboBox {
                                model: ["Select Something", "From this", "Combobox"];
                                enabled: !disable-toggle.checked;
                            }
                        }
                    }

                    GroupBox {
                        title: "Slider";
                        enabled: !disable-toggle.checked;
                        Slider {
                            minimum: -100;
                            maximum: 100;
                            value: 42;
                            enabled: !disable-toggle.checked;
                        }
                    }

                    GroupBox {
                        title: "LineEdit";
                        enabled: !disable-toggle.checked;
                        LineEdit {
                            placeholder-text: "Enter some text";
                            enabled: !disable-toggle.checked;
                        }
                    }
                }
            }
            Tab {
                title: "List View";
                GroupBox {
                    title: "StandardListView";
                    enabled: !disable-toggle.checked;
                    StandardListView {
                        model: [
                            {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                            {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                            {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                            {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                            {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                            {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                            {text: "Lorem"}, {text: "ipsum"},{text: "dolor"},{text: "sit"},{text: "amet"},{text: "consetetur"},
                        ];
                    }
                }
            }
            Tab {
                title: "TextEdit";
                VerticalLayout {
                    GroupBox {
                        title: "Word-Wrap";
                        te1 := TextEdit {
                            text: "This is our TextEdit widget, which allows for editing text that spans over multiple paragraphs.\nFor example this line starts in a new paragraph.\n\nWhen the amount of lines - due to wrapping and number of paragraphs - exceeds the available vertical height, a vertical scrollbar is shown that allows scrolling.\nYou may want to enter a bit of text here then in order to make them visible.";
                            wrap: word-wrap;
                            enabled: !disable-toggle.checked;
                        }
                    }
                     GroupBox {
                        title: "No-Wrap";
                        TextEdit {
                            text <=> te1.text;
                            wrap: no-wrap;
                            enabled: !disable-toggle.checked;
                        }
                    }
                }
            }
            Tab {
                title: "About";
                HorizontalBox {
                    alignment: center;
                    AboutSlint {
                    }
                }
            }
        }
    }
}